services:
  qdrant-service:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - event-service_default
    volumes:
      - .:/app

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - event-service_default

networks:
  event-service_default:
    external: true