services:
  api-gateway:
    build: ../api-gateway # Path to your API Gateway Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../api-gateway/.env  # Adjust path as needed
    depends_on:
      - qdrant-service
  qdrant-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
