services:
  qdrant-service:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - event-service_app-network
    volumes:
      - .:/app
networks:
  event-service_app-network:
    external: true
